const jobs = [
  {
    id: 0,
    job_title: "Sales Engineer",
    company: "Keyence Philippines Inc.",
    location: "Makati",
    salary_range: "20,000 - 30,000",
    type: "Full time",
    classification: "Business Development",
    time_posted: "less than a month ago",
    image: "keyence_logo.png",
    qualifications: [
      "Candidate must possess at least a Bachelor's Degree in any field.",
      "Willing to travel to your domestic territories for business trips",
      "Ability to communicate in English both written & oral is required",
      "Must be hardworking",
    ],
    duties: [
      "Provide technical consultation",
      "Provide service to customers",
      "Conduct product presentations and demonstrations",
      "Create sales reports top management",
    ],
  },
  {
    id: 1,
    job_title: "Sales Representative",
    company: "Thumbtack Philippines",
    location: "Manila",
    salary_range: "30,000 - 40,000",
    type: "Full time",
    classification: "Business Development",
    time_posted: "1 month ago",
    image: "thumbtack_logo.png",
    qualifications: [
      "Must have 1+ years of sales experience",
      "Prospecting and Pipeline Management experience",
      "Excellent written communication skills for non voice communication",
      "Salesforce experience",
    ],
    duties: [
      "Maintain accurate and current notes and records for all accounts in Salesforce",
      "Achieving 100% of your assigned quota while creating and cultivating a future sales pipeline",
      "Responsible for driving revenue by obtaining quota by creating and managing your pipeline",
      "Prequalify leads to determine their level of interest and fit as a potential customer",
    ],
  },
  {
    id: 2,
    job_title: "Sales Channel Manager",
    company: "Tenkie Box Concepts Inc.",
    location: "Makati",
    salary_range: "40,000 - 50,000",
    type: "Contractual",
    classification: "Business Development",
    time_posted: "2 months ago",
    image: "tenkiebox_logo.png",
    qualifications: [
      "At least 3-4 years experience in retail store operations",
      "Good leadership skills",
      "Average communication and people skills",
      "Good decision making",
    ],
    duties: [
      "Ensure store inventory is complete based on the matrix",
      "Manage the day-to-day operations of the retail stores to ensure compliance with company policies and retail operations procedures",
      "Monitors store performance and take corresponding actions to show improvement; Store Visit weekly",
      "Deals with and manages customer concerns",
    ],
  },
  {
    id: 3,
    job_title: "Data Analyst",
    company: "SSG",
    location: "Pasig",
    salary_range: "50,000 - 60,000",
    type: "Full time",
    classification: "Information Technology",
    time_posted: "less than a month ago",
    image: "ssg_logo.png",
    qualifications: [
      "Bachelor's degree in applied mathematics, Statistics, Physics, Computer Science, or related fields ",
      "Preferably 2 year's experience as Data Analyst or Report Specialist ",
      "Working knowledge with one or more programming languages (SQL, Power BI, Tableau Python, R, etc.) ",
      "Demonstrated experience applying data science methods to real-world data problems",
    ],
    duties: [
      "Lead data experiments in collaboration with the Analytics Team, fostering a collaborative and innovative work environment",
      "Develop methodology and processes for prioritization and scheduling of projects, ensuring efficient and effective project execution",
      "Analyze problems, determine root causes, and work closely with operational reports and Analytics teams to develop a long-term strategy for data platform architecture",
      "Formulate and lead guided, multifaceted analytic studies against large volumes of data, providing innovative solutions to complex data challenges",
    ],
  },
  {
    id: 4,
    job_title: "Software Engineer",
    company: "Satellite Office",
    location: "Taguig",
    salary_range: "20,000 - 30,000",
    type: "Part time",
    classification: "Information Technology",
    time_posted: "less than a month ago",
    image: "satelliteoffice_logo.png",
    qualifications: [
      "Degree in Computer Science/Software Engineering or equivalent",
      "3 years of experience in a relevant degree or field",
      "Strong Java and microservice experience",
      "Exposure to large scale distributed systems",
    ],
    duties: [
      "Collaborating with team members, including product managers and designers",
      "Communicating effectively with team members to understand project goals",
      "Testing software for functionality and performance",
      "Optimizing the performance of software applications",
    ],
  },
  {
    id: 5,
    job_title: "IT Audit",
    company: "CIS Bayad Center, Inc.",
    location: "Pasig",
    salary_range: "30,000 - 40,000",
    type: "Full time",
    classification: "Information Technology",
    time_posted: "1 month ago",
    image: "bayadcenter_logo.png",
    qualifications: [
      "Bachelor's degree in a relevant field such as Information Technology, Computer Science, Information Systems, or Accounting",
      "Certified Information Systems Auditor (CISA) from ISACA",
      "Strong understanding of IT systems, networks, and security",
      "Prior experience in IT auditing, internal auditing, or risk management",
    ],
    duties: [
      "Conduct IT and IT-related audit projects using the established IT auditing standards",
      "Process data from relevant systems for data analytics using available data analytic tools (ACL, Power BI, etc.)",
      "Identify potential risk areas that can be included in the audit scope or audit plan revision",
      "Assess internal control components of the auditee using the COSO framework",
    ],
  },
  {
    id: 6,
    job_title: "Recruitment Assistant",
    company: "Quorum International Inc.",
    location: "Pasig",
    salary_range: "40,000 - 50,000",
    type: "Part time",
    classification: "Human Resources",
    time_posted: "2 months ago",
    image: "tobys_logo.png",
    qualifications: [
      "Must be graduated with a degree in Psychology or in Human Resources or Human Behavior or Sociology",
      "Proven experience in recruitment and selection, talent acquisition, employer branding, and administrative support",
      "Strong organizational skills with the ability to multitask and prioritize",
      "Excellent written and verbal communication skills",
    ],
    duties: [
      "Help in the creation and posting of job advertisements on various platforms",
      "Review incoming job applications and resumes",
      "Conduct initial interviews for store-based positions and store operations office vacancies",
      "Conduct reference checks for potential candidates",
    ],
  },
  {
    id: 7,
    job_title: "HR Admin Assistant",
    company: "Dewan Design Office Inc.",
    location: "Pasig",
    salary_range: "40,000 - 50,000",
    type: "Part time",
    classification: "Human Resources",
    time_posted: "2 months ago",
    image: "dewan_logo.png",
    qualifications: [
      "Previous working experience as an HR administrative assistant for (3) years",
      "Ability to effectively use computer software including Microsoft Outlook, Word, Excel and HR software",
      "Knowledge of HR software (HRIS or HRMS and Recruitment Marketing platforms)",
      "Familiarity with labor laws",
    ],
    duties: [
      "Provide administrative support for HR executives",
      "Organize, compile, update company personnel records and documentation",
      "Manage and update HR databases with different information such as new hires, terminations, sick leaves, warnings, vacation, and days off",
      "Help in payroll management, preparation, and payment",
    ],
  },
  {
    id: 8,
    job_title: "Assistant HR Manager",
    company: "Unioil Petroleum Philippines, Inc.",
    location: "Manila",
    salary_range: "40,000 - 50,000",
    type: "Part time",
    classification: "Human Resources",
    time_posted: "2 months ago",
    image: "unioil_logo.png",
    qualifications: [
      "Candidate must possess at least a Bachelor's/College Degree in Human Resource Management, Psychology or equivalent",
      "At least 5 year(s) of working experience in recruitment and compensation and benefits",
      "Preferably Assistant Manager / Managers specializing in Human Resources or equivalent",
      "Working experience in Human Resources and its metrics",
    ],
    duties: [
      "Help develop and maintain a human resources system that meets the need of the organization",
      "Assist in tracking and evaluating the effectiveness of training initiatives",
      "Collaborate with HR Manager to promote a positive work environment and resolve interpersonal issues",
      "Coordinate training programs to enhance employees' skills and competencies",
    ],
  },
  {
    id: 9,
    job_title: "Civil Engineer",
    company: "BuildTech Solutions",
    location: "Manila",
    salary_range: "40,000 - 50,000",
    type: "Full time",
    classification: "Construction",
    time_posted: "less than a month ago",
    image: "buildtech.avif",
    qualifications: [
      "Bachelor's degree in Civil Engineering",
      "PRC license",
      "3 years of relevant experience",
      "Strong knowledge of construction materials and methods",
    ],
    duties: [
      "Manage construction projects",
      "Conduct site inspections",
      "Ensure compliance with safety standards",
      "Collaborate with architects and contractors to develop project plans",
    ],
  },
  {
    id: 10,
    job_title: "Construction Supervisor",
    company: "SkyHigh Builders",
    location: "Cebu City",
    salary_range: "30,000 - 40,000",
    type: "Contractual",
    classification: "Construction",
    time_posted: "1 month ago",
    image: "construction_logo.png",
    qualifications: [
      "Diploma in Construction Management",
      "5 years of supervisory experience in construction",
      "In-depth knowledge of building codes and regulations",
      "Strong communication and leadership skills",
    ],
    duties: [
      "Oversee daily construction activities",
      "Coordinate with subcontractors",
      "Report progress to project managers",
      "Ensure that construction projects are completed on time and within budget",
    ],
  },
  {
    id: 11,
    job_title: "Electrician",
    company: "PowerWired Electricals",
    location: "Davao City",
    salary_range: "20,000 - 30,000",
    type: "Part time",
    classification: "Construction",
    time_posted: "2 months ago",
    image: "powerwired_logo.png",
    qualifications: [
      "Vocational training in electrical work",
      "Valid electrician's license",
      "2 years of experience",
      "Familiarity with electrical codes and regulations",
    ],
    duties: [
      "Install and repair electrical systems",
      "Troubleshoot issues",
      "Ensure compliance with safety regulations",
      "Collaborate with other construction professionals to plan electrical installations",
    ],
  },
  {
    id: 12,
    job_title: "Architect",
    company: "Urban Designs Studio",
    location: "Makati",
    salary_range: "50,000 - 60,000",
    type: "Full time",
    classification: "Construction",
    time_posted: "less than a month ago",
    image: "urban.avif",
    qualifications: [
      "Bachelor's degree in Architecture",
      "Professional license",
      "Proficiency in CAD software",
      "Strong design and conceptualization skills",
    ],
    duties: [
      "Create architectural designs",
      "Collaborate with clients",
      "Supervise the implementation of design plans",
      "Stay updated on industry trends and incorporate innovative design concepts",
    ],
  },
  {
    id: 13,
    job_title: "Senior Accountant",
    company: "Financial Wizards Inc.",
    location: "Quezon City",
    salary_range: "50,000 - 60,000",
    type: "Full time",
    classification: "Accounting",
    time_posted: "less than a month ago",
    image: "financial_logo.png",
    qualifications: [
      "CPA license",
      "Bachelor's degree in Accounting",
      "5 years of accounting experience",
      "Knowledge of financial regulations and reporting",
    ],
    duties: [
      "Manage financial reports",
      "Oversee budgeting",
      "Ensure compliance with accounting standards",
      "Supervise accounting staff",
    ],
  },
  {
    id: 14,
    job_title: "Bookkeeper",
    company: "Numbers Crunch Corp",
    location: "Iloilo City",
    salary_range: "30,000 - 40,000",
    type: "Contractual",
    classification: "Accounting",
    time_posted: "1 month ago",
    image: "numbercrunch_logo.png",
    qualifications: [
      "Associate degree in Accounting",
      "2 years of bookkeeping experience",
      "Proficiency in QuickBooks",
      "Attention to detail and accuracy",
    ],
    duties: [
      "Maintain financial records",
      "Process invoices",
      "Reconcile accounts",
      "Prepare financial statements",
    ],
  },
  {
    id: 15,
    job_title: "Tax Consultant",
    company: "TaxSavvy Solutions",
    location: "Baguio City",
    salary_range: "40,000 - 50,000",
    type: "Full time",
    classification: "Accounting",
    time_posted: "2 months ago",
    image: "taxsavvy_logo.png",
    qualifications: [
      "Bachelor's degree in Accounting",
      "Knowledge of tax laws",
      "3 years of tax consulting experience",
      "Strong analytical and problem-solving skills",
    ],
    duties: [
      "Provide tax advice",
      "Prepare tax returns",
      "Assist clients in tax planning",
      "Stay updated on changes in tax laws",
    ],
  },
  {
    id: 16,
    job_title: "Accounts Payable Clerk",
    company: "PayLink Services",
    location: "Cagayan de Oro",
    salary_range: "20,000 - 30,000",
    type: "Part time",
    classification: "Accounting",
    time_posted: "less than a month ago",
    image: "paylink_logo.png",
    qualifications: [
      "High school diploma",
      "1 year of accounts payable experience",
      "Attention to detail",
      "Understanding of basic accounting principles",
    ],
    duties: [
      "Process vendor invoices",
      "Reconcile accounts",
      "Ensure timely payment of bills",
      "Communicate with vendors regarding payment inquiries",
    ],
  },
  {
    id: 17,
    job_title: "Registered Nurse",
    company: "HealWell Hospital",
    location: "Manila",
    salary_range: "40,000 - 50,000",
    type: "Full time",
    classification: "Medical",
    time_posted: "less than a month ago",
    image: "healwell_logo.png",
    qualifications: [
      "Bachelor's degree in Nursing",
      "PRC license",
      "BLS certification",
      "Clinical experience in a hospital setting",
    ],
    duties: [
      "Provide patient care",
      "Administer medications",
      "Collaborate with the healthcare team",
      "Assess and monitor patient conditions",
    ],
  },
  {
    id: 18,
    job_title: "Medical Technologist",
    company: "LabCare Diagnostics",
    location: "Cebu City",
    salary_range: "30,000 - 40,000",
    type: "Contractual",
    classification: "Medical",
    time_posted: "1 month ago",
    image: "labcare_logo.png",
    qualifications: [
      "Bachelor's degree in Medical Technology",
      "License from the Board of Medical Technology",
      "Experience in conducting laboratory tests",
      "Knowledge of laboratory equipment and procedures",
    ],
    duties: [
      "Conduct laboratory tests",
      "Analyze results",
      "Maintain laboratory equipment",
      "Ensure compliance with laboratory safety protocols",
    ],
  },
  {
    id: 19,
    job_title: "Physical Therapist",
    company: "MotionRehab Clinics",
    location: "Davao City",
    salary_range: "50,000 - 60,000",
    type: "Full time",
    classification: "Medical",
    time_posted: "2 months ago",
    image: "motionrehab_logo.png",
    qualifications: [
      "Doctorate in Physical Therapy",
      "License to practice",
      "3 years of clinical experience",
      "Expertise in various physical therapy techniques",
    ],
    duties: [
      "Evaluate and treat patients",
      "Develop rehabilitation plans",
      "Monitor patient progress",
      "Educate patients on therapeutic exercises",
    ],
  },
  {
    id: 20,
    job_title: "Medical Secretary",
    company: "MediServe Specialists",
    location: "Makati",
    salary_range: "20,000 - 30,000",
    type: "Part time",
    classification: "Medical",
    time_posted: "less than a month ago",
    image: "mediserve_logo.png",
    qualifications: [
      "Associate degree in Medical Office Management",
      "Strong organizational skills",
      "Knowledge of medical terminology",
      "Excellent communication and interpersonal skills",
    ],
    duties: [
      "Schedule appointments",
      "Manage medical records",
      "Assist in administrative tasks",
      "Greet and assist patients in person and over the phone",
    ],
  },
  {
    id: 21,
    job_title: "Customer Service Representative",
    company: "ServiceHub Solutions",
    location: "Quezon City",
    salary_range: "30,000 - 40,000",
    type: "Contractual",
    classification: "Call Center & Customer Service",
    time_posted: "1 month ago",
    image: "servicehub_logo.png",
    qualifications: [
      "High school diploma",
      "Excellent communication skills",
      "Customer service experience",
      "Ability to handle customer inquiries and resolve issues",
    ],
    duties: [
      "Assist customers with inquiries",
      "Resolve issues",
      "Provide information about products and services",
      "Process customer orders and returns",
    ],
  },
  {
    id: 22,
    job_title: "Technical Support Specialist",
    company: "TechAssist Inc.",
    location: "Iloilo City",
    salary_range: "40,000 - 50,000",
    type: "Full time",
    classification: "Call Center & Customer Service",
    time_posted: "2 months ago",
    image: "techassist_logo.png",
    qualifications: [
      "Bachelor's degree in IT",
      "Strong troubleshooting skills",
      "Experience in technical support",
      "Familiarity with various operating systems and software applications",
    ],
    duties: [
      "Provide technical assistance to customers",
      "Troubleshoot hardware and software issues",
      "Escalate complex problems to higher-level support teams",
      "Document and maintain records of customer issues and solutions",
    ],
  },
  {
    id: 23,
    job_title: "Sales Representative",
    company: "SalesConnect Solutions",
    location: "Baguio City",
    salary_range: "50,000 - 60,000",
    type: "Full time",
    classification: "Call Center & Customer Service",
    time_posted: "less than a month ago",
    image: "salesconnect_logo.png",
    qualifications: [
      "Bachelor's degree in Marketing",
      "Sales experience",
      "Excellent communication and negotiation skills",
      "Proven track record of meeting or exceeding sales targets",
    ],
    duties: [
      "Generate leads",
      "Pitch products/services",
      "Close sales deals",
      "Achieve and exceed sales targets",
    ],
  },
  {
    id: 24,
    job_title: "Outbound Telemarketer",
    company: "TelePromote Marketing",
    location: "Cagayan de Oro",
    salary_range: "20,000 - 30,000",
    type: "Part time",
    classification: "Call Center & Customer Service",
    time_posted: "less than a month ago",
    image: "telepromote_logo.png",
    qualifications: [
      "High school diploma",
      "Persuasive communication skills",
      "Telemarketing experience",
      "Ability to meet and exceed sales targets",
    ],
    duties: [
      "Make outbound calls",
      "Promote products/services",
      "Achieve and exceed sales targets",
      "Conduct follow-up calls to prospective clients",
    ],
  },
];

const saved_jobs = [];
const applied_jobs = [];

module.exports = { jobs, saved_jobs, applied_jobs };
